go_import_path: acs560_course_project
language: go
install: true
go:
  - "1.11"
services:
  - postgresql

script: PGPASSWORD="" PGUSER="postgres" python server_tests.py builddb && python server_tests.py testserver && python server_tests.py buildserver