version: 1.0.{build}
clone_folder: c:\gopath\src\acs560_course_project
clone_depth: 1
environment:
  GOPATH: c:\gopath
services:
  - postgresql
cache:
- client\TimeTracker\packages -> **\packages.config
install:
- set PGPASSWORD=Password12!
- set PGUSER=postgres
- PATH=C:\Program Files\PostgreSQL\10\bin\;%PATH%
- pip install future
- createdb sandbox
- createdb sandboxtest
- python server_tests.py builddb
- python server_tests.py buildclient
- python server_tests.py testserver
- python server_tests.py buildserver
build:
  verbosity: minimal
test_script:
- cmd: nunit3-console --where "namespace==TimeTracker" bin\Debug\TimeTracker.exe
