version: 1.0.7
install:
- nuget restore %APPVEYOR_BUILD_FOLDER%\Project1
build:
  verbosity: minimal
test_script:
- cmd: nunit3-console --where "class==Project1.TestStudent" Project1\bin\Release\Project1.exe