version: 1.0.9
install:
- nuget restore %APPVEYOR_BUILD_FOLDER%\Project1
cache:
- packages -> **\packages.config
build:
  verbosity: minimal
test_script:
- cmd: nunit3-console --where "class==Project1.TestStudent" Project1\bin\Debug\Project1.exe