version: 1.0.{build}
clone_folder: c:\gopath\src\acs560_course_project
clone_depth: 1
environment:
  GOPATH: c:\gopath
services:
  - postgresql
cache:
- client\TimeTracker\packages -> **\packages.config
install:
pip install future
before_build:
- set PGUSER=postgres
- set PGPASSWORD=Password12!
- PATH=C:\Program Files\PostgreSQL\10\bin\;%PATH%
- createdb sandbox
- createdb sandboxtest
build:
  verbosity: minimal
test_script:
- cmd: nunit3-console --where "namespace==TimeTracker" bin\Debug\TimeTracker.exe
