version: 1.0.11
clone_folder: c:\gopath\src\testTravis
environment:
  GOPATH: c:\gopath
install:
- nuget restore %APPVEYOR_BUILD_FOLDER%\Project1
cache:
- packages -> **\packages.config
before_build:
- sh: cd server && go build && ./server &
build:
  verbosity: minimal
test_script:
- cmd: nunit3-console --where "class==Project1.TestStudent" Project1\Project1\bin\Debug\Project1.exe