version: 1.0.21
clone_folder: c:\gopath\src\acs560_course_project
environment:
  GOPATH: c:\gopath
install:
- nuget restore %APPVEYOR_BUILD_FOLDER%\Project1
cache:
- Project1\packages -> **\packages.config
before_build:
- cd %APPVEYOR_BUILD_FOLDER%\server && go build
- cd %APPVEYOR_BUILD_FOLDER%\Project1\Project1
- copy %APPVEYOR_BUILD_FOLDER%\server\server.exe %APPVEYOR_BUILD_FOLDER%\Project1
build:
  verbosity: minimal
test_script:
- cmd: nunit3-console --where "class==Project1.TestStudent" bin\Debug\Project1.exe